### ISSUE TITLE
Disable risk difference in the forest plot

### ISSUE THREAD

**Issue by leeangling** [elong0527/forestly#101]
Can we have an option to disable risk difference in the forest plot? Sometimes, we only need to qualitatively review safety data between treatment groups. A risk difference and its confidence interval may not needed.

**Comment by elong0527** [comment]
It can be achieve by using `display` argument now.

```
meta_ae_dummy() |>
  
 prepare_ae_forestly(population = "apat",
                      observation = "wk12",
                      parameter = "any;rel;ser") |> 

format_ae_forestly(display = c("n", "prop", "fig_prop")) |> 

ae_forestly()

```
