### ISSUE TITLE
More than three treatment group

### ISSUE THREAD

**Issue by leeangling** [elong0527/forestly#102]
The tlf_ae_summary(), tlf_ae_specific(), and tidy_ae_table() didn't work when we have more than 2 treatment groups in treatment_order = c() option. It will be nice to display more than two treatment groups in the forest plot and have a option to indicate which treatment group comparison to display the risk difference.

**Comment by elong0527** [comment]
If the goal is to create an RTF table, please check `metalite.ae` that can a table with multiple group. 

https://merck.github.io/metalite.ae/articles/ae-specific.html
