### ISSUE TITLE
Independent Testing for format_ae_listing.R

### ISSUE THREAD

**Issue by burlave** [elong0527/forestly#132]
- Test plan of `propercase`:
   + `x = a`: expected output is `A`
   + `x = aa`: expected output is `Aa`
   + `x = c(aa, bb, cc)`: expected output is `Aa Bb Cc`
   + `x = 1`: expected output is `"1"`

- Test plan of `format_ae_listing`:
   + test if `"ADURN"` and `"ADURU"` is not input in pairs
   + test if all columns (expect AE, serious, sever) are title cased 
   + test if the AE, serious, sever columns are propercased, like `"Running nose"` rather than `"Running Nose"`
   + test if the output dataframe match the values from SAS

**Comment by BrianLang** [comment]
Is this issue correctly labelled and described? It seems to be for `metalite.ae`.

**Comment by wangben718** [comment]
> Is this issue correctly labelled and described? It seems to be for `metalite.ae`.

yes. I moved format_ae_listing() from `metalie.ae` to `forestly` since now it is only used for generating drill down table for interactive forest plot.

**Comment by elong0527** [comment]
I did not see this function in `forestly`. Agree with Brian the issue should be moved to `metalite.ae`.

**Comment by wangben718** [comment]
> I did not see this function in `forestly`. Agree with Brian the issue should be moved to `metalite.ae`.
> 
> [Merck/metalite.ae#93](https://github.com/Merck/metalite.ae/issues/93)
This function is in the R/ae_details.R. I moved here since we have other functions for creating AE listing now in metalite.ae. `prepare_ae_listing()` and `format_ae_listing()` are only used for drill down table in forestly now.
