### ISSUE TITLE
Independent testing: cannot snapshot the forestly()  output

### ISSUE THREAD

**Issue by wangben718** [elong0527/forestly#133]
This is the path of test file: https://github.com/elong0527/forestly/blob/master/tests/testthat/test-ae_forestly.R
Snapshot output path: https://github.com/elong0527/forestly/blob/master/tests/testthat/_snaps/ae_forestly.md

Also tried to sanp into a html file but no luck.

**Comment by elong0527** [comment]
addressed in #134.
