### ISSUE TITLE
README

### ISSUE THREAD

**Issue by elong0527** [elong0527/forestly#169]
- Let's add a GIF in the readme file to illustrate the package from user perspective.
- add link to Yujie's talk
- add link to Ben's paper

**Comment by wangben718** [comment]
![forestly](https://user-images.githubusercontent.com/85646030/236548365-331bcf24-0fd6-497b-9b20-0442ff54f9f6.gif)

**Comment by wangben718** [comment]
https://github.com/elong0527/forestly/assets/85646030/b93e8b04-5791-4c24-90ea-cfb7832442db

**Comment by wangben718** [comment]
For the paper and talk, should we add them as citation or just list their links on Readme file.

**Comment by elong0527** [comment]
Sure, please create a PR
