### ISSUE TITLE
Use https:// protocol explicitly

### ISSUE THREAD

**Issue by nanxstats** [elong0527/forestly#173]
As SSL is wide available in 2023, you should always use `https://` explicitly instead of `//` to source the remote resource, since the protocol is inherited by using `//` and has a possibility of being less secure.

This is also what I'm seeing in all CRAN packages that uses a similar pattern by searching `cdn.plot.ly` and `unpkg.com` in https://github.com/cran.

**Comment by elong0527** [comment]
Could you clarify which file have this issue? I searched the package but did not found the problem.

**Comment by nanxstats** [comment]
https://github.com/elong0527/forestly/blob/8cc134620c1688d5d99b9566f32a2528c9fc7e7f/R/html_dependency.R#L10

https://github.com/elong0527/forestly/blob/8cc134620c1688d5d99b9566f32a2528c9fc7e7f/R/html_dependency.R#L26

**Comment by elong0527** [comment]
fixed in https://github.com/elong0527/forestly/pull/178/commits/49a063d4607cf577af1eddb202869070de6b2da7
