### ISSUE TITLE
JS housekeeping

### ISSUE THREAD

**Issue by nanxstats** [elong0527/forestly#174]
- Consider renaming the directory. `javascripts` is a highly unusual name.
- Clarify source and license. If a JS file is not written by you, you should mark its source and license. You should add similar information to the JS files written by you.
- All JS code should be formatted for readability, if they are not minified.

**Comment by elong0527** [comment]
> * Consider renaming the directory. `javascripts` is a highly unusual name.

changed to `js` and updated the code. 

> * Clarify source and license. If a JS file is not written by you, you should mark its source and license. You should add similar information to the JS files written by you.

the only file that is not written by us is `plotly-min.js`, the license is in the header of the file. 

> * All JS code should be formatted for readability, if they are not minified.

Please guide how to achieve this goal? Any tool we can use?

**Comment by nanxstats** [comment]
VS Code has built-in JavaScript formatter. https://code.visualstudio.com/docs/languages/javascript#_formatting

**Comment by elong0527** [comment]
May I ask a favor to clean the javascript format? :)

**Comment by nanxstats** [comment]
Sure thing - I will send a PR.
