### ISSUE TITLE
Enable htmlwidget

### ISSUE THREAD

**Issue by elong0527** [elong0527/forestly#27]
Current javascript package is embed using `htmltools`. 

https://github.com/elong0527/forestly/blob/454eba7c803aa659ff64d2ecae2039cba153e9e7/R/sparkline_point_js.R#L55

We shall include javascript code in package source using `htmlwidgets`. 

reference: https://www.htmlwidgets.org/develop_intro.html

Materials in https://book.javascript-for-r.com/ shall be relevant

**Comment by wangben718** [comment]
https://www.r-bloggers.com/2018/01/creating-a-custom-htmlwidget-for-shiny/

**Comment by elong0527** [comment]
https://glin.github.io/reactable/articles/custom-rendering.html

**Comment by elong0527** [comment]
Nan also suggest this book as reference https://unleash-shiny.rinterface.com/htmltools-dependencies.html?q=dependenc#htmltools-dependencies

**Comment by elong0527** [comment]
Maybe we can follow https://cran.r-project.org/web/packages/reactR/vignettes/intro_htmlwidgets.html
