### ISSUE TITLE
event based count -> subject based count

### ISSUE THREAD

**Issue by LittleBeannie** [elong0527/forestly#37]
The current version of `tidy_ae_table` count the number of events, not the number of subjects. Please take a look at line #59 at https://github.com/elong0527/forestly/blob/master/R/tidy_ae_table.R#L59.

**Comment by elong0527** [comment]
Thanks, would you be able to propose a PR to fix it?

**Comment by LittleBeannie** [comment]
The solution is to replace line #59 in https://github.com/elong0527/forestly/blob/master/R/tidy_ae_table.R#L59
with `summarise(n = n_distinct(USUBJID)) %>%`.
Please double check if the logit is right. Based on my check of the output, it works correctly. 
A new PR will be committed when I finished other items in my to-do-list.

**Comment by elong0527** [comment]
Has this issue being fixed?
