### ISSUE TITLE
validate rate_compare 

### ISSUE THREAD

**Issue by elong0527** [elong0527/forestly#57]
Please start to validate `rate_compare`. It is a statistical test and you will need to read a paper to start the work. 

Miettinen, O. and Nurminen, M, \emph{Comparative Analysis of Two Rates}. Statistics in Medicine, 4:213-226, 1985.

**Comment by elong0527** [comment]
additional documentation is in https://elong0527.github.io/forestly/articles/rate_compare.html

**Comment by LittleBeannie** [comment]
See https://github.com/elong0527/forestly/blob/master/tests/testthat/test-rate_compare.R

**Comment by elong0527** [comment]
Will move the testing code into `metalite.ae`.
