### ISSUE TITLE
Range filtering in reactable

### ISSUE THREAD

**Issue by LittleBeannie** [elong0527/forestly#75]
How to add a range filter to a column (with numerical value) in reachable?

**Comment by LittleBeannie** [comment]
A similar problem is discussed in https://github.com/glin/reactable/issues/9. 

The two examples listed in the above issue are not workable, i.e., even if the numerical filter is applied, the table remains the same as the one without a filter.

The best solution remains to be explored.

**Comment by XDeng0921** [comment]
# Make the error bar = 0 if the sample size is smaller than 4
  t_display$fig_diff[(t_display$n_1 <= small_sample[1] & t_display$n_2 <= small_sample[2])] = 0
  t_display$lower[(t_display$n_1 <= small_sample[1] & t_display$n_2 <= small_sample[2])] = 0
  t_display$upper[(t_display$n_1 <= small_sample[1] & t_display$n_2 <= small_sample[2])] = 0
  
  **t_display$n_max <- pmax(t_display$n_1,t_display$n_2)
  t_display$pct_max <- pmax(t_display$pct_1,t_display$pct_2)**
  
  # Make the data frame eligible for check box design
  t_display1 <- crosstalk::SharedData$new(t_display)

    # Store the design details in a object
  design_details = forestly_design_details(t_display, 
                                           fig_prop_range, 
                                           fig_prop_label = fig_prop_label,
                                           fig_prop_color = fig_prop_color,
                                           fig_prop_colwidth = fig_prop_colwidth,
                                           fig_diff_range, 
                                           fig_diff_label = fig_diff_label,
                                           fig_diff_color = fig_diff_color,
                                           fig_diff_colwidth = fig_diff_colwidth)
  
  # Make a reactable with a select list
  p <- crosstalk::bscols(
    # Width of the select list and reactable
    widths = c(1.5, 10.5),
    **crosstalk::filter_slider("filter_incidence", "Incidence (%) in One or More Treatment Groups", t_display1, column=~pct_max, step=1, width=250,min=0,max=100),
    crosstalk::filter_slider("filter_count", "Count in One or More Treatment Groups", t_display1, column=~n_max, step=1, width=250,min=0),**
    
  # Make a select list
  crosstalk::filter_select("filter_AEcategory", "Specific AE", t_display1, ~ae_label, multiple = FALSE),

**Comment by XDeng0921** [comment]
1. Add variables in t_display for filter_slider to use:
  
  **t_display$n_max <- pmax(t_display$n_1,t_display$n_2)
  t_display$pct_max <- pmax(t_display$pct_1,t_display$pct_2)**
  
2. Add filter_slider in crosstalk::bscols():
  
  p <- crosstalk::bscols(
    widths = c(1.5, 10.5),
    crosstalk::filter_slider("filter_incidence", "Incidence (%) in One or More Treatment Groups", t_display1, column=~pct_max, step=1, width=250,min=0,max=100),
    crosstalk::filter_slider("filter_count", "Count in One or More Treatment Groups", t_display1, column=~n_max, step=1, width=250,min=0),
    crosstalk::filter_select("filter_AEcategory", "Specific AE", t_display1, ~ae_label, multiple = FALSE),
