### ISSUE TITLE
pull down listing details

### ISSUE THREAD

**Issue by LittleBeannie** [elong0527/forestly#87]
For the AE specific reactable, when we select the AE filter (e.g. drug related AE), and pull down the listing details of a specific AE (e.g. Diarrhoea), it outputs all subjects experiencing Diarrhoea, instead of subjects having drug-related Diarrhoea.

**Comment by elong0527** [comment]
Could you confirm if we can close the issue now?

**Comment by elong0527** [comment]
@wangben718, let's ensure it is addressed before we release the package.
